"use server"

import { createClient } from "@/lib/supabase/server"
import Groq from "groq-sdk"

interface TripPreferences {
  duration: string
  budget: string
  interests: string[]
  travelStyle: string
  additionalInfo: string
}

export async function generateItinerary(preferences: TripPreferences) {
  const apiKey = process.env.GROQ_API_KEY

  if (!apiKey) {
    throw new Error("Missing GROQ_API_KEY in environment variables.")
  }

  const groq = new Groq({ apiKey })

  const supabase = await createClient()

  // Fetch all destinations to provide context to the AI
  const { data: destinations } = await supabase.from("destinations").select("*")

  // Fetch cultural sites
  const { data: culturalSites } = await supabase.from("cultural_sites").select("*")

  const destinationsContext = destinations
    ?.map(
      (d) =>
        `- ${d.name} (${d.category}): ${d.description} Located in ${d.location}. ${d.featured ? "Featured destination." : ""}`,
    )
    .join("\n")

  const culturalContext = culturalSites
    ?.map((c) => `- ${c.name}: ${c.description} Located in ${c.location}.`)
    .join("\n")

  const prompt = `You are a knowledgeable travel planner specializing in Jharkhand tourism. Create a detailed, personalized itinerary based on the following preferences:

Duration: ${preferences.duration} days
Budget: ${preferences.budget}
Interests: ${preferences.interests.join(", ")}
Travel Style: ${preferences.travelStyle}
Additional Requirements: ${preferences.additionalInfo || "None"}

Available Destinations in Jharkhand:
${destinationsContext}

Cultural Sites:
${culturalContext}

Please create a day-by-day itinerary that:
1. Matches the traveler's interests and budget
2. Considers the travel style (relaxed/moderate/packed)
3. Includes specific destinations from the list above
4. Provides practical tips (best time to visit, how to reach, what to bring)
5. Suggests local food and cultural experiences
6. Includes approximate costs and time needed at each location
7. Considers travel time between destinations
8. Promotes sustainable and responsible tourism

Format the itinerary clearly with:
- Day-by-day breakdown
- Morning, afternoon, and evening activities
- Estimated costs
- Travel tips and recommendations
- Cultural etiquette notes

Make it engaging, practical, and tailored to their specific preferences.`

  try {
    const chatCompletion = await groq.chat.completions.create({
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
      model: "llama-3.3-70b-versatile",
      temperature: 1,
      max_completion_tokens: 8192,
      top_p: 1,
      stream: true,
    })

    let fullResponse = ""
    for await (const chunk of chatCompletion) {
      const content = chunk.choices[0]?.delta?.content || ""
      fullResponse += content
    }

    if (!fullResponse.trim()) {
      throw new Error("No itinerary generated by Groq.")
    }

    return fullResponse.trim()
  } catch (error) {
    console.error("[v0] Error generating itinerary:", error)
    if (error instanceof Error) {
      throw error
    }
    throw new Error("Failed to generate itinerary")
  }
}
